"""empty message

Revision ID: f4a6f75a4cca
Revises: 
Create Date: 2020-03-12 10:49:57.558300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a6f75a4cca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('company_name', sa.String(length=250), nullable=True),
    sa.Column('company_details', sa.String(length=250), nullable=True),
    sa.Column('company_vat', sa.String(length=250), nullable=True),
    sa.Column('country', sa.String(length=250), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('removed', sa.DateTime(), nullable=True),
    sa.Column('locked', sa.DateTime(), nullable=True),
    sa.Column('lock_reason', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_table('account_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_emails_email'), 'account_emails', ['email'], unique=True)
    op.create_index(op.f('ix_account_emails_expires'), 'account_emails', ['expires'], unique=False)
    op.create_index(op.f('ix_account_emails_token'), 'account_emails', ['token'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('removed', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=250), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_token'), 'api_keys', ['token'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires'), 'sessions', ['expires'], unique=False)
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_api_keys_token'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_account_emails_token'), table_name='account_emails')
    op.drop_index(op.f('ix_account_emails_expires'), table_name='account_emails')
    op.drop_index(op.f('ix_account_emails_email'), table_name='account_emails')
    op.drop_table('account_emails')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
