"""empty message

Revision ID: fb622848733a
Revises: f4a6f75a4cca
Create Date: 2020-03-12 11:09:27.222564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb622848733a'
down_revision = 'f4a6f75a4cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('uuid', sa.String(length=250), nullable=False))
    op.create_index(op.f('ix_accounts_uuid'), 'accounts', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_uuid'), table_name='accounts')
    op.drop_column('accounts', 'uuid')
    # ### end Alembic commands ###
